export default function brands() {
  const brands = [
    "Agility",
    "Bonelo",
    "Cat Chow",
    "Darwin",
    "Deleita",
    "Dog Chow",
    "Dogui",
    "Dog Selection",
    "Estampa",
    "Eukanuba",
    "Evolution",
    "Excellent",
    "Felix",
    "Gati",
    "Gaucho",
    "Gooster",
    "Iron Pet",
    "Keiko",
    "Ken L",
    "Maintenance",
    "Maussy",
    "Maxium",
    "Nature",
    "Nutribon",
    "Old Prince",
    "Pachá",
    "Pedigree",
    "Performance",
    "Profesional Vet",
    "Provet",
    "Pro Plan",
    "PupyFood",
    "Raza",
    "Royal Canin",
    "Sabrosito",
    "Sieger",
    "Siete Vidas",
    "Tiernitos",
    "Top Nutricion",
    "Ultra Pro",
    "Valiant",
    "Vagoneta",
    "Voraz",
    "Whiskas",
  ];

  return brands;
}
